version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: Ajay123
      POSTGRES_PASSWORD: Ajay123

  app:
    image: simple-docker-image:1.1
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/my_db
      SPRING_DATASOURCE_USERNAME: Ajay123
      SPRING_DATASOURCE_PASSWORD: Ajay123
    depends_on:
      - db
